/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

val BEAM_VERSION = "2.54.0"

plugins {
    id("java")
    id("application")
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation("org.apache.beam:beam-sdks-java-core:$BEAM_VERSION")
    runtimeOnly("org.apache.beam:beam-runners-direct-java:$BEAM_VERSION")
    implementation("org.apache.beam:beam-runners-flink-1.16:$BEAM_VERSION")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.0")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(19)
    }
}

tasks.shadowJar {
    setProperty("zip64", true)
    archiveFileName.set("app.jar")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}
